language: viml
sudo: required
dist: trusty

before_script:
  - git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis

script:
    - pip install --user --upgrade vim-vint pathlib enum34 typing
    - python --version
    - vim --version
    - vint --version
    - vint autoload
    - /tmp/vim-themis/bin/themis --reporter dot 
