language: viml
sudo: required
dist: trusty

script:
    - pip install --user --upgrade vim-vint pathlib enum34 typing
    - python --version
    - vim --version
    - vint --version
    - vint autoload
